name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: KevinDeBenedetti/github-workflows/.github/workflows/ci/node.yml@main
    with:
      node-version: '20'
    secrets: inherit

  deploy-preview:
    needs: ci
    if: github.event_name == 'pull_request'
    uses: KevinDeBenedetti/github-workflows/.github/workflows/cd/vercel.yml@main
    with:
      environment: preview
    secrets: inherit

  deploy-production:
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: KevinDeBenedetti/github-workflows/.github/workflows/cd/vercel.yml@main
    with:
      environment: production
    secrets: inherit

  release:
    needs: deploy-production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: KevinDeBenedetti/github-workflows/.github/workflows/release.yml@main
    secrets: inherit
