name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: KevinDeBenedetti/github-workflows/.github/workflows/ci-shell.yml@main
    with:
      run-shellcheck: false
      run-actionlint: true
      actionlint-paths: .github/workflows/
      run-bats: false
      run-link-check: true
      link-check-paths: 'docs/**/*.md'
