name: TODO sync

on:
  push:
    branches: [main]
    paths: ['TODO.yml']
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: KevinDeBenedetti/github-workflows/.github/workflows/todo-yml-push.yml@main
    secrets:
      token: ${{ secrets.PAT_TOKEN }}
